# syntax=docker/dockerfile:1

FROM golang:1.20 AS build-stage
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /fake-web-pages

FROM build-stage AS run-test-stage
RUN go tets -v ./...

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /fake-web-pages /fake-web-pages

EXPOSE 8888

USER nonroot:nonroot

ENTRYPOINT ["/fake-web-pages"]